import Head from "next/head";
import { Footer, Post, Widget } from "../components";
import {client} from '../lib/client'

export default function Home({posts}) {
  return (
    <main>
      <Head>
        <title>Shakur Galla | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <section>

        <div className="container mx-auto flex flex-wrap py-6">
        <div className="w-full md:w-2/3 flex flex-col items-center px-3">
          {posts?.map((post) =><Post key={post.title} post={post} />)}
        </div>
        
          <Widget />
        </div>
        <Footer />
      </section>
    </main>
  );
}

export const getServerSideProps = async()=>{
  const query = '*[_type == "post"] | order(_createdAt desc)'
  const posts = await client.fetch(query)

  return{
    props:{posts}
  }
}